"""Initial graph schema.

captures, nodes, edges, chunks, review_items, module_health, settings.

Revision ID: 0001
Revises:
Create Date: 2026-08-22 01:56:08.669693

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captures'))
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_uri'), ['uri'], unique=False)

    op.create_table('module_health',
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('module', name=op.f('pk_module_health'))
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_nodes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_status'), ['status'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chroma_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], name=op.f('fk_chunks_capture_id_captures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('chroma_id', name=op.f('uq_chunks_chroma_id'))
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_capture_id'), ['capture_id'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_capture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_capture_id'], ['captures.id'], name=op.f('fk_edges_evidence_capture_id_captures')),
    sa.ForeignKeyConstraint(['from_id'], ['nodes.id'], name=op.f('fk_edges_from_id_nodes')),
    sa.ForeignKeyConstraint(['to_id'], ['nodes.id'], name=op.f('fk_edges_to_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edges'))
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_from_id'), ['from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_to_id'), ['to_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_to_id'))
        batch_op.drop_index(batch_op.f('ix_edges_status'))
        batch_op.drop_index(batch_op.f('ix_edges_relation'))
        batch_op.drop_index(batch_op.f('ix_edges_from_id'))

    op.drop_table('edges')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_capture_id'))

    op.drop_table('chunks')
    op.drop_table('settings')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_status'))
        batch_op.drop_index(batch_op.f('ix_review_items_kind'))

    op.drop_table('review_items')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_nodes_kind'))
        batch_op.drop_index(batch_op.f('ix_nodes_canonical_name'))

    op.drop_table('nodes')
    op.drop_table('module_health')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_uri'))
        batch_op.drop_index(batch_op.f('ix_captures_status'))
        batch_op.drop_index(batch_op.f('ix_captures_source_type'))

    op.drop_table('captures')
    # ### end Alembic commands ###
